ARG PARENT_IMAGE_NAME=registry.gitlab.com/redmic-project/docker/redmic-server
ARG PARENT_IMAGE_TAG=latest

FROM ${PARENT_IMAGE_NAME}:${PARENT_IMAGE_TAG}

COPY /dist/*.jar ./

ARG MICROSERVICE_NAME=socket
ENV MICROSERVICE_NAME=${MICROSERVICE_NAME}

ARG MICROSERVICE_PORT=8089
ENV MICROSERVICE_PORT=${MICROSERVICE_PORT}

EXPOSE ${MICROSERVICE_PORT}
