version: '3.5'

services:
  socket:
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "${MICROSERVICE_PORT}"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: PathPrefix:/api/${MICROSERVICE_NAME};ReplacePathRegex:^/api/${MICROSERVICE_NAME}/(.*)$ /api/${MICROSERVICE_NAME}/msg/$1
        traefik.backend: ${MICROSERVICE_NAME}
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        delay: 1m
        window: 3m
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 410M
